<?php
echo "<style type='text/css' rel='stylesheet'>";
#color:
echo ".black { color: black; }";
echo ".navy { color: navy; }";
echo ".darkblue { color: darkblue; }";
echo ".mediumblue { color: mediumblue; }";
echo ".blue { color: blue; }";
echo ".darkgreen { color: darkgreen; }";
echo ".green { color: green; }";
echo ".teal { color: teal; }";
echo ".darkcyan { color: darkcyan; }";
echo ".deepskyblue { color: deepskyblue; }";
echo ".darkturquoise { color: darkturquoise; }";
echo ".mediumspringgreen { color: mediumspringgreen; }";
echo ".lime { color: lime; }";
echo ".springgreen { color: springgreen; }";
echo ".aqua { color: aqua; }";
echo ".cyan { color: cyan; }";
echo ".midnightblue { color: midnightblue; }";
echo ".dodgerblue { color: dodgerblue; }";
echo ".lightseagreen { color: lightseagreen; }";
echo ".forestgreen { color: forestgreen; }";
echo ".seagreen { color: seagreen; }";
echo ".darkslategray { color: darkslategray; }";
echo ".limegreen { color: limegreen; }";
echo ".mediumseagreen { color: mediumseagreen; }";
echo ".turquoise { color: turquoise; }";
echo ".royalblue { color: royalblue; }";
echo ".steelblue { color: steelblue; }";
echo ".darkslateblue { color: darkslateblue; }";
echo ".mediumturquoise { color: mediumturquoise; }";
echo ".indigo  { color: indigo ; }";
echo ".darkolivegreen { color: darkolivegreen; }";
echo ".cadetblue { color: cadetblue; }";
echo ".cornflowerblue { color: cornflowerblue; }";
echo ".rebeccapurple { color: rebeccapurple; }";
echo ".mediumaquamarine { color: mediumaquamarine; }";
echo ".dimgray { color: dimgray; }";
echo ".slateblue { color: slateblue; }";
echo ".olivedrab { color: olivedrab; }";
echo ".slategray { color: slategray; }";
echo ".lightslategray { color: lightslategray; }";
echo ".mediumslateblue { color: mediumslateblue; }";
echo ".lawngreen { color: lawngreen; }";
echo ".chartreuse { color: chartreuse; }";
echo ".aquamarine { color: aquamarine; }";
echo ".maroon { color: maroon; }";
echo ".purple { color: purple; }";
echo ".olive { color: olive; }";
echo ".gray { color: gray; }";
echo ".skyblue { color: skyblue; }";
echo ".lightskyblue { color: lightskyblue; }";
echo ".blueviolet { color: blueviolet; }";
echo ".darkred { color: darkred; }";
echo ".darkmagenta { color: darkmagenta; }";
echo ".saddlebrown { color: saddlebrown; }";
echo ".darkseagreen { color: darkseagreen; }";
echo ".lightgreen { color: lightgreen; }";
echo ".mediumpurple { color: mediumpurple; }";
echo ".darkviolet { color: darkviolet; }";
echo ".palegreen { color: palegreen; }";
echo ".darkorchid { color: darkorchid; }";
echo ".yellowgreen { color: yellowgreen; }";
echo ".sienna { color: sienna; }";
echo ".brown { color: brown; }";
echo ".darkgray { color: darkgray; }";
echo ".lightblue { color: lightblue; }";
echo ".greenyellow { color: greenyellow; }";
echo ".paleturquoise { color: paleturquoise; }";
echo ".lightsteelblue { color: lightsteelblue; }";
echo ".powderblue { color: powderblue; }";
echo ".firebrick { color: firebrick; }";
echo ".darkgoldenrod { color: darkgoldenrod; }";
echo ".mediumorchid { color: mediumorchid; }";
echo ".rosybrown { color: rosybrown; }";
echo ".darkkhaki { color: darkkhaki; }";
echo ".silver { color: silver; }";
echo ".mediumvioletred { color: mediumvioletred; }";
echo ".indianred  { color: indianred ; }";
echo ".peru { color: peru; }";
echo ".chocolate { color: chocolate; }";
echo ".tan { color: tan; }";
echo ".lightgray { color: lightgray; }";
echo ".thistle { color: thistle; }";
echo ".orchid { color: orchid; }";
echo ".goldenrod { color: goldenrod; }";
echo ".palevioletred { color: palevioletred; }";
echo ".crimson { color: crimson; }";
echo ".gainsboro { color: gainsboro; }";
echo ".plum { color: plum; }";
echo ".burlywood { color: burlywood; }";
echo ".lightcyan { color: lightcyan; }";
echo ".lavender { color: lavender; }";
echo ".darksalmon { color: darksalmon; }";
echo ".violet { color: violet; }";
echo ".palegoldenrod { color: palegoldenrod; }";
echo ".lightcoral { color: lightcoral; }";
echo ".khaki { color: khaki; }";
echo ".aliceblue { color: aliceblue; }";
echo ".honeydew { color: honeydew; }";
echo ".azure { color: azure; }";
echo ".sandybrown { color: sandybrown; }";
echo ".wheat { color: wheat; }";
echo ".beige { color: beige; }";
echo ".whitesmoke { color: whitesmoke; }";
echo ".mintcream { color: mintcream; }";
echo ".ghostwhite { color: ghostwhite; }";
echo ".salmon { color: salmon; }";
echo ".antiquewhite { color: antiquewhite; }";
echo ".linen { color: linen; }";
echo ".lightgoldenrodyellow { color: lightgoldenrodyellow; }";
echo ".oldlace { color: oldlace; }";
echo ".red { color: red; }";
echo ".fuchsia { color: fuchsia; }";
echo ".magenta { color: magenta; }";
echo ".deeppink { color: deeppink; }";
echo ".orangered { color: orangered; }";
echo ".tomato { color: tomato; }";
echo ".hotpink { color: hotpink; }";
echo ".coral { color: coral; }";
echo ".darkorange { color: darkorange; }";
echo ".lightsalmon { color: lightsalmon; }";
echo ".orange { color: orange; }";
echo ".lightpink { color: lightpink; }";
echo ".pink { color: pink; }";
echo ".gold { color: gold; }";
echo ".peachpuff { color: peachpuff; }";
echo ".navajowhite { color: navajowhite; }";
echo ".moccasin { color: moccasin; }";
echo ".bisque { color: bisque; }";
echo ".mistyrose { color: mistyrose; }";
echo ".blanchedalmond { color: blanchedalmond; }";
echo ".papayawhip { color: papayawhip; }";
echo ".lavenderblush { color: lavenderblush; }";
echo ".seashell { color: seashell; }";
echo ".cornsilk { color: cornsilk; }";
echo ".lemonchiffon { color: lemonchiffon; }";
echo ".floralwhite { color: floralwhite; }";
echo ".snow { color: snow; }";
echo ".yellow { color: yellow; }";
echo ".lightyellow { color: lightyellow; }";
echo ".ivory { color: ivory; }";
echo ".white { color: white; }";
#font-size:
echo ".xx-small { font-size: xx-small; }";
echo ".x-small { font-size: x-small; }";
echo ".small { font-size: small; }";
echo ".large { font-size: large; }";
echo ".x-large { font-size: x-large; }";
echo ".xx-large { font-size: xx-large; }";
#font-style:
echo ".italic { font-style: italic; }";
echo ".oblique { font-style: oblique; }";
#font-weight:
echo ".bold { font-weight: bold; }";
echo ".bolder { font-weight: bolder; }";
echo ".lighter { font-weight: lighter; }";
#text-decoration:
echo ".underline { text-decoration: underline; }";
echo ".overline { text-decoration: overline; }";
echo ".line-through { text-decoration: line-through; }";
echo "</style>";

#MAGIC HAPPENS!!11!
#$estilo="b";
#Mentira, ainda vou fazer isso. Tenho que voltar pra casa...

echo "<span class='".$estilo."'>not<span/>";
?>
